from players import Player, Position, PlayerType

year  = 2020
draft = {
    'lober'   : {1  : Player('Gurley'          , Position.RB, PlayerType.veteran ),
                 2  : Player('CMC'             , Position.RB, PlayerType.youngin),
                 3  : Player('Ty Hilton'       , Position.WR, PlayerType.veteran),
                 4  : Player('Jet McKinnon'    , Position.RB, PlayerType.youngin),
                 5  : Player('Chris Hogan'     , Position.WR, PlayerType.veteran),
                 6  : Player('Edelman'         , Position.WR, PlayerType.veteran),
                 7  : Player('Manny Sanders'   , Position.WR, PlayerType.veteran),
                 8  : Player('Delanie Walker'  , Position.TE, PlayerType.veteran),
                 9  : Player('Drew Brees'      , Position.QB, PlayerType.veteran),
                 10 : Player('Jordy Nelson'    , Position.WR, PlayerType.veteran),
                 11 : Player('Nelson Agholor'  , Position.WR, PlayerType.youngin),
                 12 : Player('Andrew Luck'     , Position.QB, PlayerType.veteran),
                 13 : Player('Jamaal Williams' , Position.RB, PlayerType.youngin),
                 14 : Player('Allen Hurns'     , Position.WR, PlayerType.youngin),
                 15 : Player('Patriots'        , Position.D , PlayerType.na     ),
                 16 : Player('Janikowski'      , Position.K , PlayerType.na     ),
                 17 : Player('James White'     , Position.RB, PlayerType.youngin)},
    
    'ben'     : {1  : Player('Lev Bell'        , Position.RB, PlayerType.veteran),
                 2  : Player('Mike Evans'      , Position.WR, PlayerType.veteran),
                 3  : Player('Dalvin Cook'     , Position.RB, PlayerType.youngin),
                 4  : Player('Jordan Howard'   , Position.RB, PlayerType.youngin),
                 5  : Player('ARob'            , Position.WR, PlayerType.youngin),
                 6  : Player('Golden Tate'     , Position.WR, PlayerType.veteran),
                 7  : Player('Alex Collins'    , Position.RB, PlayerType.youngin),
                 8  : Player('Kyle Rudolph'    , Position.TE, PlayerType.veteran),
                 9  : Player('Michael Crabtree', Position.WR, PlayerType.veteran),
                 10 : Player('Matt Stafford'   , Position.QB, PlayerType.veteran),
                 11 : Player('Dez Bryant'      , Position.WR, PlayerType.veteran),
                 12 : Player('Lagarette Blount', Position.RB, PlayerType.veteran),
                 13 : Player('Charger'         , Position.D , PlayerType.na     ),
                 14 : Player('Danny Amendola'  , Position.WR, PlayerType.veteran),
                 15 : Player('Latavius Murray' , Position.RB, PlayerType.cuff   ),
                 16 : Player('Dan Bailey'      , Position.K , PlayerType.na     ),
                 17 : Player('Cole Beasely'    , Position.WR, PlayerType.veteran)},
    
    'tiede'   : {1  : Player('Zeke'            , Position.RB, PlayerType.youngin),
                 2  : Player('AJ Green'        , Position.WR, PlayerType.veteran),
                 3  : Player('Tyreek'          , Position.WR, PlayerType.youngin),
                 4  : Player('Juju'            , Position.WR, PlayerType.youngin),
                 5  : Player('Royce Freeman'   , Position.RB, PlayerType.rookie ),
                 6  : Player('Evan Engram'     , Position.TE, PlayerType.youngin),
                 7  : Player('Mark Ingram'     , Position.RB, PlayerType.veteran),
                 8  : Player('Bobby Trees'     , Position.WR, PlayerType.youngin),
                 9  : Player('Chris Carson'    , Position.RB, PlayerType.youngin),
                 10 : Player('Jack Doyle'      , Position.TE, PlayerType.veteran),
                 11 : Player('Phil Rivers'     , Position.QB, PlayerType.veteran),
                 12 : Player('DJM'             , Position.WR, PlayerType.rookie ),
                 13 : Player('Kelvin Benjamin' , Position.WR, PlayerType.youngin),
                 14 : Player('Tarik Cohen'     , Position.RB, PlayerType.youngin),
                 15 : Player('Pat Mahomes'     , Position.QB, PlayerType.youngin),
                 16 : Player('Baltimore'       , Position.D , PlayerType.na     ),
                 17 : Player('Matt Bryan'      , Position.K , PlayerType.na     )},
    
    'aj'      : {1  : Player('David Johnson'   , Position.RB, PlayerType.youngin),
                 2  : Player('Keenan Allen'    , Position.WR, PlayerType.veteran),
                 3  : Player('Kelce'           , Position.TE, PlayerType.veteran),
                 4  : Player('Steff Diggs'     , Position.WR, PlayerType.youngin),
                 5  : Player('Russ Wilson'     , Position.QB, PlayerType.veteran),
                 6  : Player('Jay Ajayi'       , Position.RB, PlayerType.veteran),
                 7  : Player('Jamison Crowder' , Position.WR, PlayerType.veteran),
                 8  : Player('Alsho Jefferey'  , Position.WR, PlayerType.veteran),
                 9  : Player('Sony Michel'     , Position.RB, PlayerType.rookie ),
                 10 : Player('Devante Parker'  , Position.WR, PlayerType.youngin),
                 11 : Player('RoJo'            , Position.RB, PlayerType.rookie ),
                 12 : Player('Chris Thompson'  , Position.RB, PlayerType.veteran),
                 13 : Player('Patriots'        , Position.D , PlayerType.na     ),
                 14 : Player('Vance Dance'     , Position.TE, PlayerType.veteran),
                 15 : Player('Dak'             , Position.QB, PlayerType.youngin),
                 16 : Player('Nathan Peterman' , Position.QB, PlayerType.youngin),
                 17 : Player('Cris Boswell'    , Position.K , PlayerType.na     )},
    
    'falkneel': {1  : Player('AK'              , Position.RB, PlayerType.youngin),
                 2  : Player('Davante'         , Position.WR, PlayerType.veteran),
                 3  : Player('Devonte Freeman' , Position.RB, PlayerType.veteran),
                 4  : Player('Demarius Thomas' , Position.WR, PlayerType.veteran),
                 5  : Player('Deshaun Watson'  , Position.QB, PlayerType.youngin),
                 6  : Player('Brandin Cooks'   , Position.WR, PlayerType.youngin),
                 7  : Player('Derrick Henry'   , Position.RB, PlayerType.youngin),
                 8  : Player('Pierre Garcon'   , Position.WR, PlayerType.veteran),
                 9  : Player('David Njoku'     , Position.TE, PlayerType.rookie ),
                 10 : Player('Sterling Shep'   , Position.WR, PlayerType.youngin),
                 11 : Player('CJ Anderson'     , Position.RB, PlayerType.veteran),
                 12 : Player('Bilal Powell'    , Position.RB, PlayerType.veteran),
                 13 : Player('Mike Williams'   , Position.WR, PlayerType.youngin),
                 14 : Player('TJ Yeldon'       , Position.RB, PlayerType.veteran),
                 15 : Player('Chi'             , Position.D , PlayerType.na     ),
                 16 : Player('Jake Elliot'     , Position.K , PlayerType.na     ),
                 17 : Player('Blake Bortles'   , Position.QB, PlayerType.veteran)},

    'coaty'   : {1  : Player('AB'              , Position.WR, PlayerType.veteran),
                 2  : Player('Gronk'           , Position.TE, PlayerType.veteran),
                 3  : Player('Larry Fitz'      , Position.WR, PlayerType.veteran),
                 4  : Player('Tom Brady'       , Position.QB, PlayerType.veteran),
                 5  : Player('Josh Gordon'     , Position.WR, PlayerType.veteran),
                 6  : Player('Marshawn Lynch'  , Position.RB, PlayerType.veteran),
                 7  : Player('Tevin Coleman'   , Position.RB, PlayerType.veteran),
                 8  : Player('Sexy Rexy'       , Position.RB, PlayerType.veteran),
                 9  : Player('Jax'             , Position.D , PlayerType.na     ),
                 10 : Player('Gostkowski'      , Position.K , PlayerType.na     ),
                 11 : Player('Randall Cobb'    , Position.WR, PlayerType.youngin),
                 12 : Player('Jared Goff'      , Position.QB, PlayerType.youngin),
                 13 : Player('Geronimo Allison', Position.WR, PlayerType.youngin),
                 14 : Player('Aaron Jones'     , Position.RB, PlayerType.youngin),
                 15 : Player('Ty Montgomery'   , Position.RB, PlayerType.youngin),
                 16 : Player('Jared Cook'      , Position.TE, PlayerType.veteran),
                 17 : Player('Frank Gore'      , Position.RB, PlayerType.veteran)},

    'winch'   : {1  : Player('OBJ'             , Position.WR, PlayerType.veteran),
                 2  : Player('Lenny'           , Position.RB, PlayerType.veteran),
                 3  : Player('Thielen'         , Position.WR, PlayerType.veteran),
                 4  : Player('Jarvis Landry'   , Position.WR, PlayerType.veteran),
                 5  : Player('Cam'             , Position.QB, PlayerType.veteran),
                 6  : Player('Greg Olsen'      , Position.TE, PlayerType.veteran),
                 7  : Player('Kerryon'         , Position.RB, PlayerType.rookie ),
                 8  : Player('Sammy Watkins'   , Position.WR, PlayerType.veteran),
                 9  : Player('Carlos Hyde'     , Position.RB, PlayerType.veteran),
                 10 : Player('Vikings'         , Position.D , PlayerType.na     ),
                 11 : Player('Rashad Penny'    , Position.RB, PlayerType.rookie ),
                 12 : Player('OJ Howard'       , Position.TE, PlayerType.rookie ),
                 13 : Player('Greg Zurlein'    , Position.K , PlayerType.na     ),
                 14 : Player('Matt Ryan'       , Position.QB, PlayerType.veteran),
                 15 : Player('Cam Meredith'    , Position.WR, PlayerType.youngin),
                 16 : Player('Marquise Lee'    , Position.WR, PlayerType.veteran),
                 17 : Player('Spencer Ware'    , Position.RB, PlayerType.veteran)},
    
    'yonsmeet': {1  : Player('Saquon'          , Position.RB, PlayerType.rookie ),
                 2  : Player('Melvin Gordon'   , Position.RB, PlayerType.youngin),
                 3  : Player('Amari Cooper'    , Position.WR, PlayerType.youngin),
                 4  : Player('Doug Baldwin'    , Position.WR, PlayerType.veteran),
                 5  : Player('Lamar Miller'    , Position.RB, PlayerType.veteran),
                 6  : Player('Carson Wentz'    , Position.QB, PlayerType.youngin),
                 7  : Player('Trey Burton'     , Position.TE, PlayerType.youngin),
                 8  : Player('Cooper Kupp'     , Position.WR, PlayerType.youngin),
                 9  : Player('Will Fuller'     , Position.WR, PlayerType.youngin),
                 10 : Player('Peyton Barber'   , Position.RB, PlayerType.youngin),
                 11 : Player('Saints'          , Position.D , PlayerType.na     ),
                 12 : Player('Kenny Still'     , Position.WR, PlayerType.youngin),
                 13 : Player('George Kittle'   , Position.TE, PlayerType.youngin),
                 14 : Player('Kenny Golloday'  , Position.WR, PlayerType.youngin),
                 15 : Player('Marcus Mariota'  , Position.QB, PlayerType.youngin),
                 16 : Player('Justin Tucker'   , Position.K , PlayerType.na     ),
                 17 : Player('Chris Godwin'    , Position.WR, PlayerType.youngin)},
    
    'tony'    : {1  : Player('Julio'           , Position.WR, PlayerType.veteran),
                 2  : Player('Kareem Hunt'     , Position.RB, PlayerType.youngin),
                 3  : Player('Zach Ertz'       , Position.TE, PlayerType.veteran),
                 4  : Player('Kenyan Drake'    , Position.RB, PlayerType.youngin),
                 5  : Player('Marvin Jone'     , Position.WR, PlayerType.veteran),
                 6  : Player('Marquise Goodwin', Position.WR, PlayerType.youngin),
                 7  : Player('Corey Davis'     , Position.WR, PlayerType.youngin),
                 8  : Player('Robby Anderson'  , Position.WR, PlayerType.youngin),
                 9  : Player('Duke Johnson'    , Position.RB, PlayerType.youngin),
                 10 : Player('Captian Kirk'    , Position.QB, PlayerType.veteran),
                 11 : Player('Marlon Mack'     , Position.RB, PlayerType.youngin),
                 12 : Player('Philly'          , Position.D , PlayerType.na     ),
                 13 : Player('Jimmy G'         , Position.QB, PlayerType.veteran),
                 14 : Player('Eric Ebron'      , Position.TE, PlayerType.youngin),
                 15 : Player('Dede Westbrook'  , Position.WR, PlayerType.youngin),
                 16 : Player('Calvin Ridley'   , Position.WR, PlayerType.rookie ),
                 17 : Player('Matt Prater'     , Position.K , PlayerType.na     )},
    
    'tom'     : {1  : Player('MT'              , Position.WR, PlayerType.youngin),
                 2  : Player('DHop'            , Position.WR, PlayerType.youngin),
                 3  : Player('Aaron Rodgers'   , Position.QB, PlayerType.veteran),
                 4  : Player('Joe Mixon'       , Position.RB, PlayerType.youngin),
                 5  : Player('Shady'           , Position.RB, PlayerType.veteran),
                 6  : Player('Jimmy Graham'    , Position.TE, PlayerType.veteran),
                 7  : Player('Dion Lewis'      , Position.RB, PlayerType.veteran),
                 8  : Player('Devin Funchess'  , Position.WR, PlayerType.youngin),
                 9  : Player('Jordan Reed'     , Position.TE, PlayerType.veteran),
                 10 : Player('Isiah Crowell'   , Position.RB, PlayerType.veteran),
                 11 : Player('Adrian Peterson' , Position.RB, PlayerType.veteran),
                 12 : Player('Chris Ivory'     , Position.RB, PlayerType.rookie ),
                 13 : Player('Josh Doctson'    , Position.WR, PlayerType.youngin),
                 14 : Player('Nick Chubb'      , Position.RB, PlayerType.rookie ),
                 15 : Player('Martavus Bryant' , Position.WR, PlayerType.youngin),
                 16 : Player('Steelers'        , Position.D , PlayerType.na     ),
                 17 : Player('Chiefs'          , Position.D , PlayerType.na     )},
    }