from players import Player, Position, PlayerType

year  = 2020
draft = {
    'tiede'   : {1  : Player('Zeke'            , Position.RB, PlayerType.keeper ),
                 2  : Player('Kelce'           , Position.TE, PlayerType.veteran),
                 3  : Player('Golladay'        , Position.WR, PlayerType.youngin),
                 4  : Player('Ridley'          , Position.WR, PlayerType.youngin),
                 5  : Player('Lockett'         , Position.WR, PlayerType.veteran),
                 6  : Player('Rojo'            , Position.RB, PlayerType.youngin),
                 7  : Player('Hollywood'       , Position.WR, PlayerType.youngin),
                 8  : Player('Cam Akers'       , Position.RB, PlayerType.rookie ),
                 9  : Player('Diontae'         , Position.WR, PlayerType.youngin),
                 10 : Player('Duke'            , Position.RB, PlayerType.veteran),
                 11 : Player('Gibson'          , Position.RB, PlayerType.rookie ),
                 12 : Player('Boston'          , Position.RB, PlayerType.veteran),
                 13 : Player('Mecole'          , Position.WR, PlayerType.youngin),
                 14 : Player('Stafford'        , Position.QB, PlayerType.veteran),
                 15 : Player('Herndon'         , Position.TE, PlayerType.youngin),
                 16 : Player('Damein Harris'   , Position.RB, PlayerType.youngin),
                 17 : Player('Colts'           , Position.D , PlayerType.na     )},
    
    'lober'   : {1  : Player('CMC'             , Position.RB, PlayerType.keeper ),
                 2  : Player('Kittle'          , Position.TE, PlayerType.veteran),
                 3  : Player('Aaron Jones'     , Position.RB, PlayerType.youngin),
                 4  : Player('Bobby Tree'      , Position.WR, PlayerType.veteran),
                 5  : Player('Lev Bell'        , Position.RB, PlayerType.veteran),
                 6  : Player('Tyler Boyd'      , Position.WR, PlayerType.veteran),
                 7  : Player('Edelman'         , Position.WR, PlayerType.veteran),
                 8  : Player('AJ Green'        , Position.WR, PlayerType.veteran),
                 9  : Player('J Crowder'       , Position.WR, PlayerType.veteran),
                 10 : Player('Brady'           , Position.QB, PlayerType.veteran),
                 11 : Player('Hayden Hurst'    , Position.TE, PlayerType.youngin),
                 12 : Player('Rodgers'         , Position.QB, PlayerType.veteran),
                 13 : Player('Golden Tate'     , Position.WR, PlayerType.veteran),
                 14 : Player('Parris Campbell' , Position.WR, PlayerType.youngin),
                 15 : Player('Patriots'        , Position.D , PlayerType.na     ),
                 16 : Player('Bonnafon'        , Position.RB, PlayerType.cuff   ),
                 17 : Player('Younghoe'        , Position.K , PlayerType.na     )},
    
    'ben'     : {1  : Player('MT'              , Position.WR, PlayerType.keeper ),
                 2  : Player('Kenayn Drake'    , Position.RB, PlayerType.veteran),
                 3  : Player('Chubb'           , Position.RB, PlayerType.youngin),
                 4  : Player('DJM'             , Position.WR, PlayerType.youngin),
                 5  : Player('JT'              , Position.RB, PlayerType.rookie ),
                 6  : Player('TY'              , Position.WR, PlayerType.veteran),
                 7  : Player('Waller'          , Position.TE, PlayerType.youngin),
                 8  : Player('Matt Ryan'       , Position.QB, PlayerType.veteran),
                 9  : Player('MJJ'             , Position.WR, PlayerType.veteran),
                 10 : Player('Christian Kirk'  , Position.WR, PlayerType.youngin),
                 11 : Player('Tony Pollard'    , Position.RB, PlayerType.youngin),
                 12 : Player('Edmonds'         , Position.RB, PlayerType.youngin),
                 13 : Player('Hooper'          , Position.TE, PlayerType.veteran),
                 14 : Player('Josh Allen'      , Position.QB, PlayerType.youngin),
                 15 : Player('Buffalo'         , Position.D , PlayerType.na     ),
                 16 : Player('Perriman'        , Position.WR, PlayerType.veteran),
                 17 : Player('Robby Anderson'  , Position.WR, PlayerType.veteran)},
    
    'aj'      : {1  : Player('Saquon'          , Position.RB, PlayerType.keeper ),
                 2  : Player('Davante'         , Position.WR, PlayerType.veteran),
                 3  : Player('Mahomes'         , Position.QB, PlayerType.youngin),
                 4  : Player('Gurley'          , Position.RB, PlayerType.veteran),
                 5  : Player('AJB'             , Position.WR, PlayerType.youngin),
                 6  : Player('Devante Parker'  , Position.WR, PlayerType.veteran),
                 7  : Player('Gallup'          , Position.WR, PlayerType.youngin),
                 8  : Player('Mostert'         , Position.RB, PlayerType.youngin),
                 9  : Player('Hunter Henry'    , Position.TE, PlayerType.veteran),
                 10 : Player('Deebo'           , Position.WR, PlayerType.youngin),
                 11 : Player('Gronk'           , Position.TE, PlayerType.veteran),
                 12 : Player('Slayton'         , Position.WR, PlayerType.youngin),
                 13 : Player('San Fran'        , Position.D , PlayerType.na     ),
                 14 : Player('Devonta Freeman' , Position.RB, PlayerType.veteran),
                 15 : Player('Butker'          , Position.K , PlayerType.na     ),
                 16 : Player('Cam'             , Position.QB, PlayerType.veteran),
                 17 : Player('Hunter Renfrow'  , Position.WR, PlayerType.youngin)},
    
    'tom'     : {1  : Player('Hopkins'         , Position.WR, PlayerType.keeper ),
                 2  : Player('Ekeler'          , Position.RB, PlayerType.youngin),
                 3  : Player('Lamar'           , Position.QB, PlayerType.youngin),
                 4  : Player('Juju'            , Position.WR, PlayerType.youngin),
                 5  : Player('Kupp'            , Position.WR, PlayerType.veteran),
                 6  : Player('Devin Singletary', Position.RB, PlayerType.youngin),
                 7  : Player('Monty'           , Position.RB, PlayerType.youngin),
                 8  : Player('Jordan Howard'   , Position.RB, PlayerType.veteran),
                 9  : Player('Darrel Henderson', Position.RB, PlayerType.youngin),
                 10 : Player('Noah Fant'       , Position.TE, PlayerType.youngin),
                 11 : Player('Manny Sanders'   , Position.WR, PlayerType.veteran),
                 12 : Player('JJettas'         , Position.WR, PlayerType.rookie ),
                 13 : Player('Anthony Miller'  , Position.WR, PlayerType.youngin),
                 14 : Player('Sammy Watkins'   , Position.WR, PlayerType.veteran),
                 15 : Player('Hockenson'       , Position.TE, PlayerType.youngin),
                 16 : Player('KC'              , Position.D , PlayerType.na     ),
                 17 : Player('Matt Gay'        , Position.K , PlayerType.na     )},
    
    'yonsmeet': {1  : Player('Godwin'          , Position.WR, PlayerType.keeper ),
                 2  : Player('Mixon'           , Position.RB, PlayerType.youngin),
                 3  : Player('Conner'          , Position.RB, PlayerType.veteran),
                 4  : Player('Mark Andrews'    , Position.TE, PlayerType.youngin),
                 5  : Player('Terry F1'        , Position.WR, PlayerType.youngin),
                 6  : Player('David Johnson'   , Position.RB, PlayerType.veteran),
                 7  : Player('Watson'          , Position.QB, PlayerType.veteran),
                 8  : Player('Fuller'          , Position.WR, PlayerType.veteran),
                 9  : Player('Sterling Shep'   , Position.WR, PlayerType.youngin),
                 10 : Player('Zach Moss'       , Position.RB, PlayerType.rookie ),
                 11 : Player('Jonnu Smith'     , Position.TE, PlayerType.youngin),
                 12 : Player('Jalen Reagor'    , Position.WR, PlayerType.rookie ),
                 13 : Player('Desean Jax'      , Position.WR, PlayerType.veteran),
                 14 : Player('Pitt'            , Position.D , PlayerType.na     ),
                 15 : Player('Wentz'           , Position.QB, PlayerType.veteran),
                 16 : Player('Curtis Samuel'   , Position.WR, PlayerType.youngin),
                 17 : Player('Laviska'         , Position.WR, PlayerType.rookie )},
    
    'tony'    : {1  : Player('Dalvin'          , Position.RB, PlayerType.keeper ),
                 2  : Player('Josh Jacobs'     , Position.RB, PlayerType.youngin),
                 3  : Player('Thielen'         , Position.WR, PlayerType.veteran),
                 4  : Player('Ertz'            , Position.TE, PlayerType.veteran),
                 5  : Player('Mark Ingram'     , Position.RB, PlayerType.veteran),
                 6  : Player('Courtland Sutt'  , Position.WR, PlayerType.youngin),
                 7  : Player('Kyler'           , Position.QB, PlayerType.youngin),
                 8  : Player('Kareem Hunt'     , Position.RB, PlayerType.veteran),
                 9  : Player('Jared Cook'      , Position.TE, PlayerType.veteran),
                 10 : Player('Mike Williams'   , Position.WR, PlayerType.veteran),
                 11 : Player('Henry Ruggs'     , Position.WR, PlayerType.rookie ),
                 12 : Player('Preston Williams', Position.WR, PlayerType.youngin),
                 13 : Player('Latavius'        , Position.RB, PlayerType.cuff   ),
                 14 : Player('Justin Tucker'   , Position.K , PlayerType.na     ),
                 15 : Player('Justin Jackson'  , Position.RB, PlayerType.youngin),
                 16 : Player('Minn'            , Position.D , PlayerType.na     ),
                 17 : Player('Mo Sanu'         , Position.WR, PlayerType.veteran)},
    
    'falkneel': {1  : Player('AK'              , Position.RB, PlayerType.keeper ),
                 2  : Player('CEH'             , Position.RB, PlayerType.rookie ),
                 3  : Player('Mike Evans'      , Position.WR, PlayerType.veteran),
                 4  : Player('ARob'            , Position.WR, PlayerType.veteran),
                 5  : Player('DK'              , Position.WR, PlayerType.youngin),
                 6  : Player('Dak'             , Position.QB, PlayerType.youngin),
                 7  : Player('D`Andre Swift'   , Position.RB, PlayerType.rookie ),
                 8  : Player('Tyler Higbee'    , Position.TE, PlayerType.youngin),
                 9  : Player('JK Dobbins'      , Position.RB, PlayerType.rookie ),
                 10 : Player('Brandin Cooks'   , Position.WR, PlayerType.veteran),
                 11 : Player('CD Lamb'         , Position.WR, PlayerType.rookie ),
                 12 : Player('Mattison'        , Position.RB, PlayerType.cuff   ),
                 13 : Player('Phil Lindsay'    , Position.RB, PlayerType.youngin),
                 14 : Player('Aiyuk'           , Position.WR, PlayerType.rookie ),
                 15 : Player('Chi'             , Position.D , PlayerType.na     ),
                 16 : Player('Zurlein'         , Position.K , PlayerType.na     ),
                 17 : Player('Carlos Hyde'     , Position.RB, PlayerType.veteran)},
    
    'winch'   : {1  : Player('Miles Sanders'   , Position.RB, PlayerType.keeper ),
                 2  : Player('Julio'           , Position.WR, PlayerType.veteran),
                 3  : Player('Chris Carson'    , Position.RB, PlayerType.veteran),
                 4  : Player('Amari'           , Position.WR, PlayerType.veteran),
                 5  : Player('Keenan'          , Position.WR, PlayerType.veteran),
                 6  : Player('Evan Engram'     , Position.TE, PlayerType.veteran),
                 7  : Player('Russ'            , Position.QB, PlayerType.veteran),
                 8  : Player('Jarvis'          , Position.WR, PlayerType.veteran),
                 9  : Player('John Brown'      , Position.WR, PlayerType.veteran),
                 10 : Player('Marlon Mack'     , Position.RB, PlayerType.veteran),
                 11 : Player('Mike Gesicki'    , Position.TE, PlayerType.youngin),
                 12 : Player('Tarik Cohen'     , Position.RB, PlayerType.veteran),
                 13 : Player('Jerry Jeudy'     , Position.WR, PlayerType.rookie ),
                 14 : Player('Bal'             , Position.D , PlayerType.na     ),
                 15 : Player('Robbie Gould'    , Position.K , PlayerType.na     ),
                 16 : Player('Jared Goff'      , Position.QB, PlayerType.veteran),
                 17 : Player('Adrian Peterson' , Position.RB, PlayerType.veteran)},
    
    'coaty'   : {1  : Player('Yeti'            , Position.RB, PlayerType.keeper ),
                 2  : Player('Tyreek'          , Position.WR, PlayerType.veteran),
                 3  : Player('Melvin'          , Position.RB, PlayerType.veteran),
                 4  : Player('OBJ'             , Position.WR, PlayerType.veteran),
                 5  : Player('Lenny'           , Position.RB, PlayerType.veteran),
                 6  : Player('DJ Chark'        , Position.WR, PlayerType.youngin),
                 7  : Player('Steff Diggs'     , Position.WR, PlayerType.youngin),
                 8  : Player('James White'     , Position.RB, PlayerType.veteran),
                 9  : Player('Drew Brees'      , Position.QB, PlayerType.veteran),
                 10 : Player('Matt Breida'     , Position.RB, PlayerType.youngin),
                 11 : Player('Kerryon'         , Position.RB, PlayerType.youngin),
                 12 : Player('Tevin Coleman'   , Position.RB, PlayerType.veteran),
                 13 : Player('Nkeal'           , Position.WR, PlayerType.youngin),
                 14 : Player('Allen Lazard'    , Position.WR, PlayerType.youngin),
                 15 : Player('AJ Dillon'       , Position.RB, PlayerType.rookie ),
                 16 : Player('Will Lutz'       , Position.K , PlayerType.na     ),
                 17 : Player('Nathan Peterman' , Position.QB, PlayerType.na     )}
    }